server:
  # 服务器端口号
  port: 8009
  servlet:
    context-path: /

spring:
  datasource:
    # 配置连接池
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crm
    username: root
    password: root
    hikari:
      auto-commit: true
      maximum-pool-size: 30
      connection-test-query: select 1
      connection-timeout: 5000
      data-source-properties:
        cachePrepStmts: true
        dataSource.cachePrepStmts: true
        dataSource.prepStmtCacheSize: 250
        dataSource.prepStmtCacheSqlLimit: 2048
        dataSource.userServerPrepStmts: true
  data:
    redis:
      host: 172.29.255.213
      port: 6379
      database: 0

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
